name: food_prime_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.5.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/app_image_1.png
    - assets/app_image_2.png
    - assets/app_image_3.png
    - assets/app_logo.png
    - assets/burger_popular_1.png
    - assets/burger_popular_2.png
    - assets/burger_popular_3.png
    - assets/burger_popular_4.png
    - assets/burger_popular_5.png
    - assets/burger_special_1.png
    - assets/burger_special_2.png
    - assets/burger_special_3.png
    - assets/burger_special_4.png
    - assets/empty_cart.png
    - assets/facebook_logo.png
    - assets/fruit_1.png
    - assets/fruit_10.png
    - assets/fruit_2.png
    - assets/fruit_3.png
    - assets/fruit_4.png
    - assets/fruit_5.png
    - assets/fruit_6.png
    - assets/fruit_7.png
    - assets/fruit_8.png
    - assets/fruit_9.png
    - assets/google_logo.png
    - assets/home_image_1.png
    - assets/home_image_2.png
    - assets/kitchen_1.png
    - assets/kitchen_2.png
    - assets/kitchen_3.png
    - assets/kitchen_4.png
    - assets/kitchen_5.png
    - assets/kitchen_6.png
    - assets/kitchen_7.png
    - assets/linkedin_logo.png
    - assets/master_card.png
    - assets/no_notifications.png
    - assets/onboarding_1.png
    - assets/onboarding_2.png
    - assets/onboarding_3.png
    - assets/order_successful.png
    - assets/paypal.png
    - assets/pizza_popular_1.png
    - assets/pizza_popular_2.png
    - assets/pizza_popular_3.png
    - assets/pizza_popular_4.png
    - assets/pizza_popular_5.png
    - assets/pizza_special_1.png
    - assets/pizza_special_2.png
    - assets/pizza_special_3.png
    - assets/pizza_special_4.png
    - assets/premium_1.png
    - assets/premium_2.png
    - assets/premium_3.png
    - assets/premium_4.png
    - assets/sandwich_popular_1.png
    - assets/sandwich_popular_2.png
    - assets/sandwich_popular_3.png
    - assets/sandwich_popular_4.png
    - assets/sandwich_popular_5.png
    - assets/sandwich_special_1.png
    - assets/sandwich_special_2.png
    - assets/sandwich_special_3.png
    - assets/sandwich_special_4.png
    - assets/user_profile.png
    - assets/vegetable_1.png
    - assets/vegetable_10.png
    - assets/vegetable_2.png
    - assets/vegetable_3.png
    - assets/vegetable_4.png
    - assets/vegetable_5.png
    - assets/vegetable_6.png
    - assets/vegetable_7.png
    - assets/vegetable_8.png
    - assets/vegetable_9.png
    - assets/visa.png
    - assets/word_app_logo.png
    - assets/word_app_logo_food.svg
